### PR TITLE
 fix: fix bug causing the url to FOS/SecurityAdvisories original commit being incorrect

### PR DESCRIPTION
**Pull request by azjezz**

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Weird: build is stuck again.

**Comment by Ocramius** [comment]
That's because I'm a potato 🤦

https://github.com/Roave/SecurityAdvisoriesBuilder/blob/bdbeed5c4e9dc0cdd9454e892b33491ed3ceba4d/.github/workflows/quality_check.yml#L3

**Comment by azjezz** [comment]
fixed

**Review by Ocramius — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
