### PR TITLE
Auto-deploy to heroku

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by Ocramius** [comment]
Works: https://roave-security-advisories.herokuapp.com/

**Comment by asgrim** [comment]
Uhh interesting; I pinged the URL and it generated a new build already, so let's hope nothing broke :fearful: 
Also; no build here?

**Comment by asgrim** [comment]
FWIW, output from the URL was:

```
{"before":"1d921dcf1d2ed33e42ef416429ea58b8a69e7c1d","after":"5d73e147181b1961dea86beb89686d75027690cc"}
```

**Comment by Ocramius** [comment]
Generating new builds shouldn't be a problem 👌

**Pull request merged**
