### PR TITLE
Upgraded to @azjezz /psl:^2.0.0-rc2, upgraded to PHP 8.1

### PR DESCRIPTION
**Pull request by Ocramius**

### CODE REVIEW

**Comment by Ocramius** [comment]
Interesting: mutation list increased, so this needs more work.

**Comment by Ocramius** [comment]
@azjezz I would expect these to fail static analysis:

```diff
 5) /home/runner/work/SecurityAdvisoriesBuilder/SecurityAdvisoriesBuilder/src/Roave/SecurityAdvisories/AdvisorySources/GetAdvisoriesFromFriendsOfPhp.php:59    [M] ArrayItem

--- Original
+++ New
@@ @@
     public function __invoke() : Generator
     {
         return yield from Vec\map($this->getAdvisoryFiles(), static function (SplFileInfo $advisoryFile) : Advisory {
-            $definition = Type\shape(['branches' => Type\dict(Type\array_key(), Type\shape(['versions' => Type\union(Type\string(), Type\vec(Type\string()))], true)), 'reference' => Type\string()], true)->assert(Yaml::parse(File\read(Type\non_empty_string()->assert($advisoryFile->getRealPath())), Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE));
+            $definition = Type\shape(['branches' => Type\dict(Type\array_key(), Type\shape(['versions' > Type\union(Type\string(), Type\vec(Type\string()))], true)), 'reference' => Type\string()], true)->assert(Yaml::parse(File\read(Type\non_empty_string()->assert($advisoryFile->getRealPath())), Yaml::PARSE_EXCEPTION_ON_INVALID_TYPE));
             return Advisory::fromArrayData($definition);
         });
     }
```

In practice, `Type\shape([false, ...])` should probably not work, right? :thinking:

**Comment by azjezz** [comment]
> In practice, Type\shape([false, ...]) should probably not work, right? 🤔

Yes... it's `Type\shape<T>(array<Tk, TypeInterface<Tv>> $elements, bool $allow_unknown_fields = false): TypeInterface<array<Tk, Tv>>`, so even without psl plugin, it should fail.

**Comment by Ocramius** [comment]
Ok, smells like a bug in `roave/infection-static-analysis-plugin` - that mutant makes no sense :thinking:

**Review by Ocramius — COMMENTED** [review]
:ship:

**Pull request merged**
