### PR TITLE
revert depending on a Composer dev release

### PR DESCRIPTION
**Pull request by xabbuh**
Composer 2.6.6 has been released so depending on a development version is no longer necessary.

### CODE REVIEW

**Comment by xabbuh** [comment]
partially reverting #743 now that Composer 2.6.6 has been published

**Comment by Ocramius** [comment]
Lock file please 😁

**Comment by xabbuh** [comment]
oh no, not again 😆

**Review by Ocramius — APPROVED** [review]
Thanks!

**Pull request merged**
