### PR TITLE
force install as dev requirement

### LINKED ISSUE #110: force install as dev-requirement
Composer has a mechanism to allow a package to enforce to be a dev-requirement, rather than a non-dev-requirement

read <https://getcomposer.org/doc/04-schema.md#keywords>
> Some special keywords trigger `composer require` without the `--dev` option to prompt users if they would like to add these packages to `require-dev` instead of `require`. These are: `dev`, `testing`, `static analysis`.

All documentation of this project state that this is should be a dev-requirement.
Let's enforce it. I propose to add the keyword `dev` to the manifest `composer.json`.

### PR DESCRIPTION
**Pull request by jkowalleck**
fixes https://github.com/Roave/SecurityAdvisories/issues/110

### CODE REVIEW

**Comment by Ocramius** [comment]
One tiny CS issue left 😁

**Comment by jkowalleck** [comment]
sorry for the trial/error pushes.
unfortunately, the code style checker/rules are not runnable locally, or are they?

**Comment by Ocramius** [comment]
They should be: I re-ran the pipeline though

**Comment by jkowalleck** [comment]
> They should be: I re-ran the pipeline though

got `phpcs` running locally, it seems to be passing.

**Review by Ocramius — APPROVED** [review]
Thanks @jkowalleck!

**Pull request merged**
