### PR TITLE
Removed composer.phar installation, already installed composer assumed

### LINKED ISSUE #388: Remove `composer install` manual step when executing `build-conflicts.php`
The manual composer installation is a relic of the past, when this was running on heroku: 

https://github.com/Roave/SecurityAdvisoriesBuilder/blob/f1e921206b2843842506e90a66d86c2b3f199ce9/build-conflicts.php#L217-L221

We should assume the `composer` binary to be available.

Ref: https://github.com/Roave/SecurityAdvisoriesBuilder/pull/386#discussion_r637546139

### PR DESCRIPTION
**Pull request by slash3b**
This PR covers [issues/388](https://github.com/Roave/SecurityAdvisoriesBuilder/issues/388)

Fixes #388

### CODE REVIEW

**Comment by slash3b** [comment]
It is too late and I might not think straight... why the heck quality action is not running upon PR creation?

**Comment by slash3b** [comment]
> It is too late and I might not think straight... why the heck quality action is not running upon PR creation?

okay sorry for the noise, it is running on my branch — https://github.com/slash3b/SecurityAdvisoriesBuilder/runs/2659484192?check_suite_focus=true 

Is this confusing only for me? Is it used to be visible in the PR as well ? :thinking:

**Comment by Ocramius** [comment]
Sorry @slash3b, I totally forgot to merge this one @_@

**Comment by Ocramius** [comment]
I did a mess while rebasing - opened a new PR with your commits @ #452

**Pull request closed without merging**
